# Generated by Django 2.2.2 on 2019-06-28 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('synthacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='particpant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='synthacks.Player'),
        ),
    ]
