# Generated by Django 2.2.2 on 2019-06-28 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthacks', '0002_team_particpant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='particpant',
        ),
        migrations.RemoveField(
            model_name='team',
            name='teamname',
        ),
        migrations.AddField(
            model_name='team',
            name='first_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='first_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='second_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='second_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='third_grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='third_name',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
